import os

params = {'HSX' : {'general_option' : 1,
                   'points_number' : 1,
                   'follow_type' : 1,
                   'points_dphi' : 0.017453292519943295,
                   'n_iter' : 36000,
                   'output_coils' : 0,
                   'log_freq' : 1,
                   'num_main_coils' : 0,
                   'vessel_file' : '',
                   'mgrid_file' : os.path.join('/mnt','HSX_Database','HSX_Configs','coil_data','mgrid_hsx_wmain.nc'),
                   'num_periods' : 4,
                   'is_mirrored' : 0,
                   'skip_value' : 1,
                   'num_aux_coils' : 0,
                   'use_diffusion' : 0,
                   'd_perp' : 0.5,
                   'temperature' : 80,
                   'num_divertors' : 0,
                   'num_limiters' : 0,
                   'mgrid_currents' : '-10722.0 -10722.0 -10722.0 -10722.0 -10722.0 -10722.0 0.0 0.0 0.0 0.0 0.0 0.0'},

          'W7X' : {'general_option' : 1,
                   'points_number' : 1,
                   'follow_type' : 1,
                   'points_dphi' : 0.017453292519943295,
                   'n_iter' : 36000,
                   'output_coils' : 0,
                   'log_freq' : 1,
                   'num_main_coils' : 0,
                   'mgrid_file' : os.path.join('/home','michael','Desktop', 'flf', 'python_wrapper', 'mgrid_w7x.nc'),
                   'num_periods' : 5,
                   'is_mirrored' : 0,
                   'skip_value' : 1,
                   'num_aux_coils' : 0,
                   'use_diffusion' : 0,
                   'd_perp' : 0.5,
                   'temperature' : 80,
                   'num_divertors' : 0,
                   'num_limiters' : 0,
                   'mgrid_currents' : '14042.  11795.  10250.  11795.  11654.   -421.   -421.'},

          'ETOS' : {'general_option' : 1,
                    'points_number' : 1,
                    'follow_type' : 1,
                    'points_dphi' : 0.017453292519943295,
                    'n_iter' : 36000,
                    'output_coils' : 0,
                    'log_freq' : 1,
                    'num_main_coils' : 0,
                    'vessel_file': '',
                    'mgrid_file' : '/home/michael/Desktop/for_thomas/mgrid_etos_506.nc',
                    'num_periods' : 5,
                    'is_mirrored' : 0,
                    'skip_value' : 1,
                    'num_aux_coils' : 0,
                    'use_diffusion' : 0,
                    'd_perp' : 0.5,
                    'temperature' : 80,
                    'num_divertors' : 0,
                    'num_limiters' : 0,
                    'mgrid_currents' : '10000 -2857.14'},

          'Helicotor' : {'general_option' : 1,
                         'points_number' : 1,
                         'follow_type' : 1,
                         'points_dphi' : 0.017453292519943295,
                         'n_iter' : 36000,
                         'output_coils' : 0,
                         'log_freq' : 1,
                         'num_main_coils' : 0,
                         'mgrid_file' : 'itos_coils/mgrid_helicotor_wmain.nc',
                         'num_periods' : 1,
                         'is_mirrored' : 0,
                         'skip_value' : 1,
                         'num_aux_coils' : 0,
                         'use_diffusion' : 0,
                         'd_perp' : 0.5,
                         'temperature' : 80,
                         'num_divertors' : 0,
                         'num_limiters' : 0,
                         'mgrid_currents' : '1000. 1000. 1000. 1000. 1000. 1000. 1000. 1000.'}
          }
